version: "3"
services:
  app:
    container_name: dev_nomad_typescript
    build:
      context: ./
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
    - ./:/app
    # ports:
    # - "3000:3000"
    networks:
    - dev_nomad_typescript_network
networks:
  dev_nomad_typescript_network:
